import type {
  Organisation, Account, Transaction, RecurringPayment,
  InsightCard, PaymentApproval, MonthlyBurn, KPIs, ChatMessage,
} from './types'

// ─── Organisation ─────────────────────────────────────────────────────────────
export const mockOrg: Organisation = {
  id: 'org_techflow',
  name: 'TechFlow Labs',
  logoUrl: undefined,
  employeeCount: 12,
  stripeCustomerId: 'cus_Qx3kLmN8pR2wT',
  businessType: 'software',
  createdAt: '2023-06-14T10:00:00Z',
}

// ─── Accounts ─────────────────────────────────────────────────────────────────
export const mockAccounts: Account[] = [
  {
    id: 'acc_boi',
    plaidItemId: 'item_boi_001',
    name: 'Business Current',
    officialName: 'Bank of Ireland Business Current Account',
    institution: 'Bank of Ireland',
    institutionColor: '#0E4FA8',
    type: 'checking',
    currency: 'EUR',
    currentBalance: 47230.50,
    availableBalance: 45980.00,
    lastSynced: new Date(Date.now() - 2 * 60000).toISOString(),
  },
  {
    id: 'acc_revolut',
    plaidItemId: 'item_rev_001',
    name: 'Revolut Business',
    officialName: 'Revolut Business — Main',
    institution: 'Revolut',
    institutionColor: '#191C1F',
    type: 'checking',
    currency: 'EUR',
    currentBalance: 38920.00,
    availableBalance: 38920.00,
    lastSynced: new Date(Date.now() - 1 * 60000).toISOString(),
  },
  {
    id: 'acc_wise',
    plaidItemId: 'item_wise_001',
    name: 'Wise Multi-Currency',
    officialName: 'Wise Business EUR Account',
    institution: 'Wise',
    institutionColor: '#9FE870',
    type: 'checking',
    currency: 'EUR',
    currentBalance: 12840.75,
    availableBalance: 12840.75,
    lastSynced: new Date(Date.now() - 5 * 60000).toISOString(),
  },
]

// ─── KPIs ─────────────────────────────────────────────────────────────────────
export const mockKPIs: KPIs = {
  totalCashPosition: 98991.25,
  runway: 6.5,           // months — amber zone
  monthlyBurn: 15230,
  burnTrend: 8.3,        // +8.3% vs last month
  dueSoon: 4200,
  dueSoonCount: 3,
  financialHealthScore: 68,
}

// ─── Burn Rate Chart (6 months) ───────────────────────────────────────────────
export const mockBurnData: MonthlyBurn[] = [
  { month: 'Aug', burn: 12400, revenue: 18000, net: 5600 },
  { month: 'Sep', burn: 13100, revenue: 19500, net: 6400 },
  { month: 'Oct', burn: 14200, revenue: 20000, net: 5800 },
  { month: 'Nov', burn: 13800, revenue: 22000, net: 8200 },
  { month: 'Dec', burn: 14100, revenue: 21500, net: 7400 },
  { month: 'Jan', burn: 15230, revenue: 23000, net: 7770 },
]

// ─── Category Breakdown ───────────────────────────────────────────────────────
export const mockCategories = [
  { name: 'Infrastructure',  amount: 4380, pct: 28.8, color: '#2C2926' },
  { name: 'Software & Services',    amount: 2840, pct: 18.6, color: '#E87878' },
  { name: 'Payroll',         amount: 5200, pct: 34.1, color: '#7AC0A8' },
  { name: 'Marketing',       amount: 1200, pct: 7.9,  color: '#6898C8' },
  { name: 'Office & Rent',   amount: 800,  pct: 5.3,  color: '#C89850' },
  { name: 'Other',           amount: 810,  pct: 5.3,  color: '#888888' },
]

// ─── Transactions (last 90 days, most recent first) ───────────────────────────
export const mockTransactions: Transaction[] = [
  {
    id: 'txn_001', accountId: 'acc_boi',
    amount: -2100, currency: 'EUR', date: '2025-01-28',
    merchantName: 'Häfele Hardware Supply', merchantLogoUrl: undefined,
    helmCategory: 'Infrastructure', pending: false, recurringId: 'rec_aws',
  },
  {
    id: 'txn_002', accountId: 'acc_revolut',
    amount: -89, currency: 'EUR', date: '2025-01-25',
    merchantName: 'Blum Components', merchantLogoUrl: undefined,
    helmCategory: 'Infrastructure', pending: false, recurringId: 'rec_vercel',
  },
  {
    id: 'txn_003', accountId: 'acc_boi',
    amount: 23000, currency: 'EUR', date: '2025-01-24',
    merchantName: 'Stripe Payout — Revenue', merchantLogoUrl: 'https://logo.clearbit.com/stripe.com',
    helmCategory: 'Revenue', pending: false,
  },
  {
    id: 'txn_004', accountId: 'acc_boi',
    amount: -160, currency: 'EUR', date: '2025-01-22',
    merchantName: 'QuickBooks', merchantLogoUrl: undefined,
    helmCategory: 'Software & Services', pending: false, recurringId: 'rec_notion',
  },
  {
    id: 'txn_005', accountId: 'acc_revolut',
    amount: -2600, currency: 'EUR', date: '2025-01-20',
    merchantName: 'Payroll — Jan (Batch 1)', merchantLogoUrl: undefined,
    helmCategory: 'Payroll', pending: false,
  },
  {
    id: 'txn_006', accountId: 'acc_boi',
    amount: -2600, currency: 'EUR', date: '2025-01-20',
    merchantName: 'Payroll — Jan (Batch 2)', merchantLogoUrl: undefined,
    helmCategory: 'Payroll', pending: false,
  },
  {
    id: 'txn_007', accountId: 'acc_revolut',
    amount: -120, currency: 'EUR', date: '2025-01-18',
    merchantName: 'Adobe Creative Cloud', merchantLogoUrl: undefined,
    helmCategory: 'Software & Services', pending: false, recurringId: 'rec_google',
  },
  {
    id: 'txn_008', accountId: 'acc_boi',
    amount: -84, currency: 'EUR', date: '2025-01-17',
    merchantName: 'Xero Accounting', merchantLogoUrl: undefined,
    helmCategory: 'Software & Services', pending: false, recurringId: 'rec_github',
  },
  {
    id: 'txn_009', accountId: 'acc_boi',
    amount: -800, currency: 'EUR', date: '2025-01-15',
    merchantName: 'Warehouse Dublin', merchantLogoUrl: undefined,
    helmCategory: 'Office & Rent', pending: false, recurringId: 'rec_office',
  },
  {
    id: 'txn_010', accountId: 'acc_revolut',
    amount: -340, currency: 'EUR', date: '2025-01-14',
    merchantName: 'Stripe Processing Fees', merchantLogoUrl: 'https://logo.clearbit.com/stripe.com',
    helmCategory: 'Software & Services', pending: false,
  },
  {
    id: 'txn_011', accountId: 'acc_boi',
    amount: -1890, currency: 'EUR', date: '2025-01-10',
    merchantName: 'IKEA Industry Supply', merchantLogoUrl: undefined,
    helmCategory: 'Infrastructure', pending: false, recurringId: 'rec_gcp',
  },
  {
    id: 'txn_012', accountId: 'acc_revolut',
    amount: -80, currency: 'EUR', date: '2025-01-09',
    merchantName: 'ShipStation', merchantLogoUrl: undefined,
    helmCategory: 'Software & Services', pending: false, recurringId: 'rec_linear',
  },
  {
    id: 'txn_013', accountId: 'acc_wise',
    amount: -1200, currency: 'EUR', date: '2025-01-08',
    merchantName: 'Meta Ads — Campaign Q1', merchantLogoUrl: 'https://logo.clearbit.com/meta.com',
    helmCategory: 'Marketing', pending: false,
  },
  {
    id: 'txn_014', accountId: 'acc_boi',
    amount: -391, currency: 'EUR', date: '2025-01-07',
    merchantName: 'Häfele Hardware Supply', merchantLogoUrl: undefined,
    helmCategory: 'Infrastructure', pending: false,
  },
]

// ─── Recurring Payments ───────────────────────────────────────────────────────
export const mockRecurring: RecurringPayment[] = [
  {
    id: 'rec_aws',
    merchantName: 'Häfele Hardware Supply',
    merchantLogoUrl: undefined,
    averageAmount: 2100,
    currency: 'EUR',
    frequency: 'monthly',
    lastPaymentDate: '2025-01-28',
    nextExpectedDate: '2025-02-28',
    totalYtd: 2100,
    helmCategory: 'Infrastructure',
    status: 'pending_approval',
    autoPayEnabled: false,
    usageFlag: 'active',
  },
  {
    id: 'rec_gcp',
    merchantName: 'IKEA Industry Supply',
    merchantLogoUrl: undefined,
    averageAmount: 1890,
    currency: 'EUR',
    frequency: 'monthly',
    lastPaymentDate: '2025-01-10',
    nextExpectedDate: '2025-02-10',
    totalYtd: 1890,
    helmCategory: 'Infrastructure',
    status: 'active',
    autoPayEnabled: true,
    usageFlag: 'active',
  },
  {
    id: 'rec_notion',
    merchantName: 'QuickBooks',
    merchantLogoUrl: undefined,
    averageAmount: 160,
    currency: 'EUR',
    frequency: 'monthly',
    lastPaymentDate: '2025-01-22',
    nextExpectedDate: '2025-02-22',
    totalYtd: 160,
    helmCategory: 'Software & Services',
    status: 'under_review',
    autoPayEnabled: false,
    usageFlag: 'low',
  },
  {
    id: 'rec_google',
    merchantName: 'Adobe Creative Cloud',
    merchantLogoUrl: undefined,
    averageAmount: 120,
    currency: 'EUR',
    frequency: 'monthly',
    lastPaymentDate: '2025-01-18',
    nextExpectedDate: '2025-02-18',
    totalYtd: 120,
    helmCategory: 'Software & Services',
    status: 'pending_approval',
    autoPayEnabled: false,
    usageFlag: 'active',
  },
  {
    id: 'rec_vercel',
    merchantName: 'Blum Components',
    merchantLogoUrl: undefined,
    averageAmount: 89,
    currency: 'EUR',
    frequency: 'monthly',
    lastPaymentDate: '2025-01-25',
    nextExpectedDate: '2025-02-25',
    totalYtd: 89,
    helmCategory: 'Infrastructure',
    status: 'active',
    autoPayEnabled: true,
    usageFlag: 'active',
  },
  {
    id: 'rec_github',
    merchantName: 'Xero Accounting',
    merchantLogoUrl: undefined,
    averageAmount: 84,
    currency: 'EUR',
    frequency: 'monthly',
    lastPaymentDate: '2025-01-17',
    nextExpectedDate: '2025-02-17',
    totalYtd: 84,
    helmCategory: 'Software & Services',
    status: 'active',
    autoPayEnabled: true,
    usageFlag: 'active',
  },
  {
    id: 'rec_linear',
    merchantName: 'ShipStation',
    merchantLogoUrl: undefined,
    averageAmount: 80,
    currency: 'EUR',
    frequency: 'monthly',
    lastPaymentDate: '2025-01-09',
    nextExpectedDate: '2025-02-09',
    totalYtd: 80,
    helmCategory: 'Software & Services',
    status: 'under_review',
    autoPayEnabled: false,
    usageFlag: 'unused',
  },
  {
    id: 'rec_office',
    merchantName: 'Warehouse Dublin',
    merchantLogoUrl: undefined,
    averageAmount: 800,
    currency: 'EUR',
    frequency: 'monthly',
    lastPaymentDate: '2025-01-15',
    nextExpectedDate: '2025-02-15',
    totalYtd: 800,
    helmCategory: 'Office & Rent',
    status: 'active',
    autoPayEnabled: true,
    usageFlag: 'active',
  },
]

// ─── Approval Queue ───────────────────────────────────────────────────────────
export const mockApprovals: PaymentApproval[] = [
  {
    id: 'appr_001',
    recurringId: 'rec_aws',
    merchantName: 'Häfele Hardware Supply',
    merchantLogoUrl: undefined,
    helmCategory: 'Infrastructure',
    expectedAmount: 2100,
    expectedAmountMax: 2310,
    expectedDate: '2025-02-28',
    lastPaidAmount: 2100,
    lastPaidDate: '2025-01-28',
    status: 'pending',
  },
  {
    id: 'appr_002',
    recurringId: 'rec_google',
    merchantName: 'Adobe Creative Cloud',
    merchantLogoUrl: undefined,
    helmCategory: 'Software & Services',
    expectedAmount: 120,
    expectedAmountMax: 120,
    expectedDate: '2025-02-18',
    lastPaidAmount: 120,
    lastPaidDate: '2025-01-18',
    status: 'pending',
  },
  {
    id: 'appr_003',
    recurringId: 'rec_gusto',
    merchantName: 'Gusto Payroll',
    merchantLogoUrl: undefined,
    helmCategory: 'Payroll',
    expectedAmount: 18400,
    expectedAmountMax: 18400,
    expectedDate: '2025-02-28',
    lastPaidAmount: 17950,
    lastPaidDate: '2025-01-31',
    status: 'pending',
  },
  {
    id: 'appr_004',
    recurringId: 'rec_gcp',
    merchantName: 'Google Cloud Platform',
    merchantLogoUrl: undefined,
    helmCategory: 'Infrastructure',
    expectedAmount: 3740,
    expectedAmountMax: 4200,
    expectedDate: '2025-03-01',
    lastPaidAmount: 3740,
    lastPaidDate: '2025-02-01',
    status: 'pending',
  },
  {
    id: 'appr_005',
    recurringId: 'rec_office',
    merchantName: 'WeWork — Schöneberg',
    merchantLogoUrl: undefined,
    helmCategory: 'Office & Rent',
    expectedAmount: 4200,
    expectedAmountMax: 4200,
    expectedDate: '2025-03-01',
    lastPaidAmount: 4200,
    lastPaidDate: '2025-02-01',
    status: 'pending',
  },
]

// ─── Insight Cards ────────────────────────────────────────────────────────────
export const mockInsights: InsightCard[] = [
  {
    id: 'ins_001',
    type: 'anomaly',
    headline: 'Häfele spend up 41% vs last month',
    body: 'Your supplier bill jumped from €1,488 to €2,100. This is above your 3-month average. Worth investigating before next order cycle.',
    actionLabel: 'Review transactions',
    dismissed: false,
    generatedAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    urgency: 'high',
  },
  {
    id: 'ins_002',
    type: 'runway',
    headline: 'Cash reserves drop below 6 months on Mar 14',
    body: 'At €15,230/mo in costs, you\'ll cross the 6-month cash reserves threshold in ~6 weeks. Consider a credit line renegotiation or cost review now.',
    actionLabel: 'View cash forecast',
    dismissed: false,
    generatedAt: new Date(Date.now() - 4 * 3600000).toISOString(),
    urgency: 'high',
  },
  {
    id: 'ins_003',
    type: 'subscription',
    headline: 'ShipStation & QuickBooks have 4 idle seats',
    body: 'Based on activity patterns, 2 ShipStation seats and 2 QuickBooks seats haven\'t been used in 45+ days. Downgrading saves ~€52/mo.',
    actionLabel: 'Review seats',
    dismissed: false,
    generatedAt: new Date(Date.now() - 6 * 3600000).toISOString(),
    urgency: 'medium',
  },
  {
    id: 'ins_004',
    type: 'saving',
    headline: 'Switch to annual billing, save €890',
    body: 'QuickBooks, Xero and ShipStation all offer 2 months free on annual plans. Based on your usage, switching today saves €890 over 12 months.',
    actionLabel: 'See breakdown',
    dismissed: false,
    generatedAt: new Date(Date.now() - 8 * 3600000).toISOString(),
    urgency: 'low',
  },
  {
    id: 'ins_005',
    type: 'margin',
    headline: 'Gross margin improved 3.2% this month',
    body: 'Revenue grew 7% while total costs grew 3.7%. Your cost efficiency is improving. Keep this trajectory for 2 more months to reach break-even.',
    dismissed: false,
    generatedAt: new Date(Date.now() - 10 * 3600000).toISOString(),
    urgency: 'low',
  },
]

// ─── AI Chat Seed ─────────────────────────────────────────────────────────────
export const mockChatHistory: ChatMessage[] = [
  {
    id: 'msg_001',
    role: 'user',
    content: 'Which subscriptions are we probably not using?',
    timestamp: new Date(Date.now() - 25 * 60000).toISOString(),
  },
  {
    id: 'msg_002',
    role: 'assistant',
    content: 'Based on transaction patterns, **ShipStation** and **QuickBooks** both show low engagement signals:\n\n• **ShipStation** — paid €80/mo, but no shipping activity in 45 days across 2 seats\n• **QuickBooks** — paid €160/mo, 2 of 10 seats show zero activity in 6 weeks\n\nDowngrading both to smaller plans saves approximately **€52/month** (€624/year).\n\nWant me to flag these in your recurring payments for review?',
    timestamp: new Date(Date.now() - 24 * 60000).toISOString(),
  },
]
